=== mitesh777/servletsAndWeb/XMLPractice/bin/airlineDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT airlines (airline)*>
<!ELEMENT airline ((id | airlineId), name,serviceType?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT airlineId (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT serviceType (#PCDATA)>

=== mitesh777/servletsAndWeb/XMLPractice/bin/XMLAirlines.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE airlines SYSTEM "airlineDTD.dtd">
<airlines>
	<airline>
		<id>1</id>
		<name> SkillAssure air</name>
		<serviceType>Domestic</serviceType>
	</airline>
	<airline>
		<airlineId>2</airlineId>
		<name> Pratian air</name>
		<serviceType>International</serviceType>
	</airline>
</airlines>
